export interface Movie {
  id: string;
  title: string;
  type: 'movie' | 'show';
  genres: string[];
  rating: number;
  releaseYear: number;
  description: string;
  director: string;
  cast: string[];
  posterUrl: string;
  backdropUrl: string;
  duration?: number;
  seasons?: number;
  episodes?: number;
}

export const movies: Movie[] = [
  {
    id: 'the-shawshank-redemption',
    title: 'The Shawshank Redemption',
    type: 'movie',
    genres: ['Drama', 'Crime'],
    rating: 9.3,
    releaseYear: 1994,
    description: 'The Shawshank Redemption is a classic drama about banker Andy Dufresne, wrongly convicted of murder in 1947 and sentenced to life at the harsh Shawshank Penitentiary, where he forms a deep friendship with inmate "Red". Over two decades, Andy endures prison brutality, uses his financial skills to help the corrupt warden, and quietly maintains hope, all while secretly planning an escape and exploring themes of perseverance, injustice, and friendship. ',
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    posterUrl: 'https://cdn.kinocheck.com/i/x26a82drmk.jpg',
    backdropUrl: 'https://images.justwatch.com/backdrop/305223517/s640/the-shawshank-redemption',
    duration: 142,
  },
  {
    id: 'the-godfather',
    title: 'The Godfather',
    type: 'movie',
    genres: ['Crime', 'Drama'],
    rating: 9.2,
    releaseYear: 1972,
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his youngest and most reluctant son.',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    backdropUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQWcX_vvkiyzlAcjuu6wDse0nwjULcWYypIg&s',
    duration: 175,
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight',
    type: 'movie',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 9.0,
    releaseYear: 2008,
    description: 'When the menace known as The Joker unleashes his reign of chaos and terror on Gotham, Batman must accept one of the greatest psychological tests.',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStSrkl4OLvST4y_f-fz56oL5olr-DCvJ2cWQ&s',
    backdropUrl: 'https://images.pexels.com/photos/3532553/pexels-photo-3532553.jpeg',
    duration: 152,
  },
  {
    id: 'pulp-fiction',
    title: 'Pulp Fiction',
    type: 'movie',
    genres: ['Crime', 'Drama'],
    rating: 8.9,
    releaseYear: 1994,
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
    backdropUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQowsgGNAM5KYyTn9vvGjCeqZjKqq2MxBKDcQ&s',
    duration: 154,
  },
  {
    id: 'forrest-gump',
    title: 'Forrest Gump',
    type: 'movie',
    genres: ['Drama', 'Romance'],
    rating: 8.8,
    releaseYear: 1994,
    description: 'The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with an IQ of 75.',
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Sally Field', 'Gary Sinise'],
    posterUrl: 'https://images.pexels.com/photos/3532552/pexels-photo-3532552.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532552/pexels-photo-3532552.jpeg',
    duration: 142,
  },
  {
    id: 'inception',
    title: 'Inception',
    type: 'movie',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    rating: 8.8,
    releaseYear: 2010,
    description: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    posterUrl: 'https://images.pexels.com/photos/3532551/pexels-photo-3532551.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532551/pexels-photo-3532551.jpeg',
    duration: 148,
  },
  {
    id: 'the-matrix',
    title: 'The Matrix',
    type: 'movie',
    genres: ['Action', 'Sci-Fi'],
    rating: 8.7,
    releaseYear: 1999,
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    director: 'The Wachowskis',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZGM1NDM3MTAtMmI0ZC00ZDAwLWEwY2EtNDdhYjZmMjJkNzM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    backdropUrl: 'https://images.pexels.com/photos/1116148/pexels-photo-1116148.jpeg',
    duration: 136,
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    type: 'movie',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 8.6,
    releaseYear: 2014,
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    posterUrl: 'https://www.slamedia.org/wp-content/uploads/2014/11/interstellar-feat.jpeg',
    backdropUrl: 'https://substackcdn.com/image/fetch/$s_!7B_m!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4e914015-c791-48c7-865c-6c495968dcfb_957x535.png',
    duration: 169,
  },
  {
    id: 'fight-club',
    title: 'Fight Club',
    type: 'movie',
    genres: ['Drama'],
    rating: 8.8,
    releaseYear: 1999,
    description: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into much more.',
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    posterUrl: 'https://rukminim2.flixcart.com/image/480/480/xif0q/poster/t/m/w/small-spos11804-poster-fight-club-brad-pitt-movie-sl11804-wall-original-imaghyv4uaxyafzg.jpeg?q=90',
    backdropUrl: 'https://images.pexels.com/photos/1116146/pexels-photo-1116146.jpeg',
    duration: 139,
  },
  {
    id: 'goodfellas',
    title: 'Goodfellas',
    type: 'movie',
    genres: ['Crime', 'Drama'],
    rating: 8.7,
    releaseYear: 1990,
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.',
    director: 'Martin Scorsese',
    cast: ['Robert De Niro', 'Ray Liotta', 'Paul Sorvino'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXEsEMzMVKE81QSbBiAh65v03Q3n7GTvKXEw&s',
    backdropUrl: 'https://images.pexels.com/photos/1116145/pexels-photo-1116145.jpeg',
    duration: 146,
  },
  {
    id: 'the-silence-of-the-lambs',
    title: 'The Silence of the Lambs',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.6,
    releaseYear: 1991,
    description: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
    director: 'Jonathan Demme',
    cast: ['Jodie Foster', 'Scott Glenn', 'Anthony Hopkins'],
    posterUrl: 'https://s3.amazonaws.com/criterion-production/films/46014912ca0c20592c472f5bbe33e4f8/L9AQ95Y7z2vOIUf1ntwvpZsZx3kp8B_original.jpg',
    backdropUrl: 'https://images.pexels.com/photos/1116144/pexels-photo-1116144.jpeg',
    duration: 118,
  },
  {
    id: 'saving-private-ryan',
    title: 'Saving Private Ryan',
    type: 'movie',
    genres: ['Drama', 'War'],
    rating: 8.6,
    releaseYear: 1998,
    description: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.',
    director: 'Steven Spielberg',
    cast: ['Tom Hanks', 'Edward Burns', 'Tom Sizemore'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzdFj21HBCymrQM50F9Hykneh3cS3UhoIxbA&s',
    backdropUrl: 'https://images.pexels.com/photos/1116143/pexels-photo-1116143.jpeg',
    duration: 169,
  },
  {
    id: 'breaking-bad',
    title: 'Breaking Bad',
    type: 'show',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 9.5,
    releaseYear: 2008,
    description: 'A high school chemistry teacher turned meth cook partners with a former student to produce crystal meth.',
    director: 'Vince Gilligan',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    posterUrl: 'https://media.s-bol.com/rJgD2NxgXw6/550x763.jpg',
    backdropUrl: 'https://www.slashfilm.com/img/gallery/what-happened-to-the-cast-of-breaking-bad/l-intro-1726787962.jpg',
    seasons: 5,
    episodes: 62,
  },
  {
    id: 'game-of-thrones',
    title: 'Game of Thrones',
    type: 'show',
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    rating: 9.3,
    releaseYear: 2011,
    description: 'Nine noble families fight for control over the magical lands of Westeros, while an ancient enemy awakens.',
    director: 'David Benioff, D.B. Weiss',
    cast: ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington'],
    posterUrl: 'https://images.pexels.com/photos/3532549/pexels-photo-3532549.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532549/pexels-photo-3532549.jpeg',
    seasons: 8,
    episodes: 73,
  },
  {
    id: 'sherlock',
    title: 'Sherlock',
    type: 'show',
    genres: ['Crime', 'Drama', 'Mystery'],
    rating: 9.1,
    releaseYear: 2010,
    description: 'A modern update of the classic detective stories about Sherlock Holmes and Dr. Watson.',
    director: 'Mark Gatiss, Steven Moffat',
    cast: ['Benedict Cumberbatch', 'Martin Freeman', 'Rupert Graves'],
    posterUrl: 'https://images.pexels.com/photos/3532548/pexels-photo-3532548.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532548/pexels-photo-3532548.jpeg',
    seasons: 4,
    episodes: 13,
  },
  {
    id: 'the-crown',
    title: 'The Crown',
    type: 'show',
    genres: ['Biography', 'Drama', 'History'],
    rating: 8.6,
    releaseYear: 2016,
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
    director: 'Peter Morgan',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
    posterUrl: 'https://images.pexels.com/photos/3532547/pexels-photo-3532547.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532547/pexels-photo-3532547.jpeg',
    seasons: 6,
    episodes: 50,
  },
  {
    id: 'stranger-things',
    title: 'Stranger Things',
    type: 'show',
    genres: ['Drama', 'Fantasy', 'Horror', 'Mystery'],
    rating: 8.7,
    releaseYear: 2016,
    description: 'When a young boy disappears, his friends uncover a mystery involving secret government experiments and terrifying supernatural forces.',
    director: 'The Duffer Brothers',
    cast: ['Winona Ryder', 'David Harbour', 'Finn Wolfhard'],
    posterUrl: 'https://images.pexels.com/photos/3532546/pexels-photo-3532546.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532546/pexels-photo-3532546.jpeg',
    seasons: 4,
    episodes: 42,
  },
  {
    id: 'the-office',
    title: 'The Office',
    type: 'show',
    genres: ['Comedy'],
    rating: 9.0,
    releaseYear: 2005,
    description: 'A mockumentary about the lives of office workers in a mundane paper supply company.',
    director: 'Greg Daniels',
    cast: ['Steve Carell', 'Rainn Wilson', 'Jenna Fischer'],
    posterUrl: 'https://images.pexels.com/photos/3532545/pexels-photo-3532545.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532545/pexels-photo-3532545.jpeg',
    seasons: 9,
    episodes: 201,
  },
  {
    id: 'true-detective',
    title: 'True Detective',
    type: 'show',
    genres: ['Crime', 'Drama', 'Mystery'],
    rating: 8.9,
    releaseYear: 2014,
    description: 'An anthology series featuring stand-alone crime dramas with different settings and characters in each season.',
    director: 'Nic Pizzolatto',
    cast: ['Matthew McConaughey', 'Woody Harrelson', 'Colin Farrell'],
    posterUrl: 'https://images.pexels.com/photos/3532544/pexels-photo-3532544.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532544/pexels-photo-3532544.jpeg',
    seasons: 4,
    episodes: 24,
  },
  {
    id: 'westworld',
    title: 'Westworld',
    type: 'show',
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    rating: 8.5,
    releaseYear: 2016,
    description: 'At a futuristic theme park populated by android host robots, wealthy guests can live out any fantasy in a western setting.',
    director: 'Jonathan Nolan, Lisa Joy',
    cast: ['Evan Rachel Wood', 'James Marsden', 'Ed Harris'],
    posterUrl: 'https://images.pexels.com/photos/3532543/pexels-photo-3532543.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/3532543/pexels-photo-3532543.jpeg',
    seasons: 4,
    episodes: 36,
  },
  //st pasting movie from gpt
  {
    id: 'the-lord-of-the-rings-fellowship',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    type: 'movie',
    genres: ['Adventure', 'Fantasy'],
    rating: 8.8,
    releaseYear: 2001,
    description: "A young hobbit, Frodo, inherits a powerful ring and must journey across Middle-earth to destroy it before darkness returns.",
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 178,
  },
  {
    id: 'gladiator',
    title: 'Gladiator',
    type: 'movie',
    genres: ['Action', 'Drama'],
    rating: 8.5,
    releaseYear: 2000,
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    director: 'Ridley Scott',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 155,
  },
  {
    id: 'the-lion-king-1994',
    title: 'The Lion King',
    type: 'movie',
    genres: ['Animation', 'Adventure', 'Drama'],
    rating: 8.5,
    releaseYear: 1994,
    description: 'A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.',
    director: 'Roger Allers, Rob Minkoff',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 88,
  },
  {
    id: 'the-prestige',
    title: 'The Prestige',
    type: 'movie',
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    rating: 8.5,
    releaseYear: 2006,
    description: 'Two rival magicians in Victorian London engage in a bitter battle for supremacy — at great cost to both of them.',
    director: 'Christopher Nolan',
    cast: ['Hugh Jackman', 'Christian Bale', 'Scarlett Johansson'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 130,
  },
  {
    id: 'se7en',
    title: 'Se7en',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Mystery'],
    rating: 8.6,
    releaseYear: 1995,
    description: 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.',
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 127,
  },
  {
    id: 'parasite',
    title: 'Parasite',
    type: 'movie',
    genres: ['Drama', 'Thriller'],
    rating: 8.6,
    releaseYear: 2019,
    description: 'Greed and class discrimination threaten the newly formed relationship between the wealthy Park family and the poor Kim clan.',
    director: 'Bong Joon Ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 132,
  },
  {
    id: 'joker-2019',
    title: 'Joker',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.4,
    releaseYear: 2019,
    description: 'A failed comedian descends into madness and transforms into the criminal mastermind known as the Joker.',
    director: 'Todd Phillips',
    cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 122,
  },
  {
    id: 'la-la-land',
    title: 'La La Land',
    type: 'movie',
    genres: ['Comedy', 'Drama', 'Music'],
    rating: 8.0,
    releaseYear: 2016,
    description: 'A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles.',
    director: 'Damien Chazelle',
    cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 128,
  },
  {
    id: 'the-departed',
    title: 'The Departed',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.5,
    releaseYear: 2006,
    description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 151,
  },
  {
    id: 'whiplash',
    title: 'Whiplash',
    type: 'movie',
    genres: ['Drama', 'Music'],
    rating: 8.5,
    releaseYear: 2014,
    description: 'A promising young drummer enrolls at a cutthroat music conservatory where his instructor pushes him to the edge.',
    director: 'Damien Chazelle',
    cast: ['Miles Teller', 'J.K. Simmons'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 106,
  },
  {
    id: 'mad-max-fury-road',
    title: 'Mad Max: Fury Road',
    type: 'movie',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.1,
    releaseYear: 2015,
    description: "In a post-apocalyptic wasteland, Max joins Furiosa to flee a tyrant and his army in a spectacular road chase.",
    director: 'George Miller',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    posterUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    backdropUrl: 'https://images.pexels.com/photos/1116136/pexels-photo-1116136.jpeg',
    duration: 120,
  }
];

export function getAllMovies(): Movie[] {
  return movies;
}

export function getMovieById(id: string): Movie | undefined {
  return movies.find(m => m.id === id);
}

export function getMoviesByGenre(genre: string): Movie[] {
  return movies.filter(m => m.genres.includes(genre));
}

export function getAllGenres(): string[] {
  const genreSet = new Set<string>();
  movies.forEach(m => {
    m.genres.forEach(g => genreSet.add(g));
  });
  return Array.from(genreSet).sort();
}

export function getTopRatedMovies(limit: number = 10): Movie[] {
  return [...movies].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getMoviesByType(type: 'movie' | 'show'): Movie[] {
  return movies.filter(m => m.type === type);
}
